/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.Factura;

/**
 *
 * @author Domenica
 */
public class AnularFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form AnularFactura
     */
    public AnularFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCedC5 = new javax.swing.JLabel();
        txtCedC5 = new javax.swing.JTextField();
        lblCodC5 = new javax.swing.JLabel();
        txtCodC5 = new javax.swing.JTextField();
        lblNomC5 = new javax.swing.JLabel();
        txtNomC5 = new javax.swing.JTextField();
        lblTelC5 = new javax.swing.JLabel();
        txtTelC5 = new javax.swing.JTextField();
        txtApeC5 = new javax.swing.JTextField();
        lblApeC5 = new javax.swing.JLabel();
        lblDirC5 = new javax.swing.JLabel();
        txtDirC5 = new javax.swing.JTextField();
        lblRuc = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        txtRuc = new javax.swing.JTextField();
        lblTot = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnCancelarF = new javax.swing.JButton();
        txtFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServF = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        lblSub = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblIva = new javax.swing.JLabel();
        btnBuscarCF5 = new javax.swing.JButton();

        jPanel1.setMinimumSize(new java.awt.Dimension(450, 500));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCedC5.setBackground(new java.awt.Color(255, 255, 255));
        lblCedC5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCedC5.setText("Cedula Cliente");

        txtCedC5.setEditable(false);
        txtCedC5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        lblCodC5.setBackground(new java.awt.Color(255, 255, 255));
        lblCodC5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCodC5.setText("Codigo Cliente");

        txtCodC5.setEditable(false);
        txtCodC5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCodC5.setEnabled(false);

        lblNomC5.setBackground(new java.awt.Color(255, 255, 255));
        lblNomC5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblNomC5.setText("Nombre Cliente");

        txtNomC5.setEditable(false);
        txtNomC5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtNomC5.setEnabled(false);

        lblTelC5.setBackground(new java.awt.Color(255, 255, 255));
        lblTelC5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblTelC5.setText("Telefono Cliente");

        txtTelC5.setEditable(false);
        txtTelC5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTelC5.setEnabled(false);

        txtApeC5.setEditable(false);
        txtApeC5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtApeC5.setEnabled(false);

        lblApeC5.setBackground(new java.awt.Color(255, 255, 255));
        lblApeC5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblApeC5.setText("Apellido Cliente");

        lblDirC5.setBackground(new java.awt.Color(255, 255, 255));
        lblDirC5.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblDirC5.setText("Direccion Cliente");

        txtDirC5.setEditable(false);
        txtDirC5.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtDirC5.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblTelC5)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelC5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNomC5)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomC5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCedC5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedC5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCodC5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodC5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblApeC5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApeC5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lblDirC5)
                            .addGap(18, 18, 18)
                            .addComponent(txtDirC5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedC5)
                    .addComponent(txtCedC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodC5)
                    .addComponent(txtCodC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblApeC5)
                        .addComponent(txtApeC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomC5)
                        .addComponent(txtNomC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDirC5)
                        .addComponent(txtDirC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelC5)
                        .addComponent(txtTelC5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRuc.setBackground(new java.awt.Color(255, 255, 255));
        lblRuc.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblRuc.setText("RUC Factura");

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtIva.setEnabled(false);

        txtRuc.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        lblTot.setBackground(new java.awt.Color(255, 255, 255));
        lblTot.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblTot.setText("Total");

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblFecha.setText("Fecha");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTotal.setEnabled(false);

        lblTitulo.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        lblTitulo.setText("Anular Factura");

        btnCancelarF.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btnCancelarF.setText("Cancelar");
        btnCancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFActionPerformed(evt);
            }
        });

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtFecha.setEnabled(false);

        tblServF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "0", null, null, null, null}
            },
            new String [] {
                "codigo", "cantidad", "nombre", "precio u", "IvaProducto", "totalIP"
            }
        ));
        tblServF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblServFKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblServF);

        btnCrear.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btnCrear.setText("Anular");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblSub.setBackground(new java.awt.Color(255, 255, 255));
        lblSub.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblSub.setText("Subtotal");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtSubtotal.setEnabled(false);

        lblIva.setBackground(new java.awt.Color(255, 255, 255));
        lblIva.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblIva.setText("I.V.A");

        btnBuscarCF5.setText("Buscar");
        btnBuscarCF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCF5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrear)
                .addGap(34, 34, 34)
                .addComponent(btnCancelarF)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSub)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIva)
                                .addGap(16, 16, 16)
                                .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTot)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(lblTitulo))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblRuc)
                        .addGap(18, 18, 18)
                        .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCF5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblRuc))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFecha)
                                .addComponent(btnBuscarCF5)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSub))
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIva)
                        .addComponent(btnCrear)
                        .addComponent(btnCancelarF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTot))
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFActionPerformed
        // TODO add your handling code here:
        /*        x = null;
        this.dispose();*/
    }//GEN-LAST:event_btnCancelarFActionPerformed

    private void tblServFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServFKeyReleased

        /*int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            int fila = tblServF.getSelectedRow();
            int columna = tblServF.getSelectedColumn();
            int codigoServ = 0;

            Object[] datos1 = {"", 0, "", "", ""};

            if (columna == 0) {
                codigoServ = Integer.parseInt(tblServF.getValueAt(fila, columna).toString());
                servicio = controladorServicio.read(codigoServ);

                int cant = Integer.parseInt(tblServF.getValueAt(fila, 1).toString());

                tablaF = (DefaultTableModel) tblServF.getModel();
                tablaF.removeRow(fila);
                totalCP = cant * servicio.getPrecio();

                Object[] datos = {codigoServ,
                    cant,
                    servicio.getNombreservicio(),
                    servicio.getPrecio(),
                    totalCP
                };

                tablaF.addRow(datos);
                tablaF.addRow(datos1);
            } else if (columna == 1) {

                codigoServ = Integer.parseInt(tblServF.getValueAt(fila, columna - 1).toString());
                int cant = Integer.parseInt(tblServF.getValueAt(fila, columna).toString());
                tablaF.removeRow(fila);
                tablaF.removeRow(tblServF.getRowCount() - 1);

                totalCP = cant * servicio.getPrecio();

                Object[] datos = {codigoServ,
                    cant,
                    servicio.getNombreservicio(),
                    servicio.getPrecio(),
                    totalCP
                };

                tablaF.addRow(datos);
                tablaF.addRow(datos1);

            }

            subtotal = subtotal + totalCP;
            txtSubtotal.setText(String.valueOf(subtotal));

            iva = subtotal * 0.12;
            txtIva.setText(String.valueOf(iva));

            total = subtotal + iva;
            txtTotal.setText(String.valueOf(total));

        }*/
    }//GEN-LAST:event_tblServFKeyReleased

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        /*//obtener fecha
        fecha = new Date();

        //obtener clases
        String cedulaC = txtCedC.getText();
        cliente = controladorCliente.readCedula(cedulaC);

        String cedulaV = txtCedV.getText();
        veterinario = controladorVeterinario.readCedula(cedulaV);

        int codigoM = Integer.parseInt(txtCodM.getText());
        mascota = controladorMascota.read(codigoM);

        //agregarDatos
        factura.setFecha(fecha);

        //clases
        factura.setVet(veterinario);
        factura.setCli(cliente);
        factura.setMasc(mascota);

        //facDetalle
        for (int i = 0; i < tblServF.getRowCount() - 1; i++) {
            System.out.println("i " + i);
            facDet = new FDetalle();

            double cant = Integer.parseInt(tblServF.getValueAt(i, 1).toString());
            int cant1 = (int) cant;
            facDet.setCantidad(cant1);

            //facDet.setCodigo(Integer.parseInt(tblServF.getValueAt(i, 0).toString()));
            //int codigoS = ;
            //facDet.setServ(controladorServicio.read(Integer.parseInt(tblServF.getValueAt(i, 0).toString())));
            facDet.setServ(controladorServicio.read(Integer.parseInt(tblServF.getValueAt(i, 0).toString())));
            factura.añadirFacDetalle(facDet);
            //            controladorFDetalle.create(facDet);

        }

        llenarDatos();
        //factura
        factura.setSubtotal(subtotal);
        factura.setIva(iva);
        factura.setTotal(total);

        controladorFactura.create(factura);
        JOptionPane.showMessageDialog(this, "Factura Creada");
        System.out.println("factura \n" + factura.toString());
        /*
        txtRuc.setText(Integer.toString(controladorFactura.getCodigo()));
        factura.setRuc(Integer.parseInt(txtRuc.getText()));

        int ruc = this.controladorFactura.getCodigo() + 1;
        txtRuc.setText(String.valueOf(ruc));
        txtFecha.setText(controladorFactura.getFecha());

        contador = 0;

        vaciarDatos();
        vaciarTabla();*/
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarCF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCF5ActionPerformed

        /* String cedula = txtCedC.getText();
        cliente = controladorCliente.read1(cedula);

        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Cedula no Existe");
        } else {
            //txtCodC.setText(Integer.toString(cliente.getCodigo()));
            txtNomC.setText(cliente.getNombre());
            txtApeC.setText(cliente.getApellido());
            txtDirC.setText(cliente.getDireccion());
            txtTelC.setText(cliente.getTelefono());
        }*/
    }//GEN-LAST:event_btnBuscarCF5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCF5;
    private javax.swing.JButton btnCancelarF;
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApeC5;
    private javax.swing.JLabel lblCedC5;
    private javax.swing.JLabel lblCodC5;
    private javax.swing.JLabel lblDirC5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNomC5;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTelC5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTot;
    private javax.swing.JTable tblServF;
    private javax.swing.JTextField txtApeC5;
    private javax.swing.JTextField txtCedC5;
    private javax.swing.JTextField txtCodC5;
    private javax.swing.JTextField txtDirC5;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNomC5;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelC5;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
